package example;

/**
* example/fibonacciHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Sistemas/Documents/NetBeansProjects/Corba/CorbaFiboInterface/src/fibonacci.idl
* jueves 20 de julio de 2023 12:08:11 Hora de Colombia
*/

public final class fibonacciHolder implements org.omg.CORBA.portable.Streamable
{
  public example.fibonacci value = null;

  public fibonacciHolder ()
  {
  }

  public fibonacciHolder (example.fibonacci initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = example.fibonacciHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    example.fibonacciHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return example.fibonacciHelper.type ();
  }

}
