package example;


/**
* example/fibonacci.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Sistemas/Documents/NetBeansProjects/Corba/CorbaFiboInterface/src/fibonacci.idl
* jueves 20 de julio de 2023 12:08:11 Hora de Colombia
*/

public interface fibonacci extends fibonacciOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface fibonacci
